### PR TITLE
Change expection of  key `errors` with array of errors messages to `errorMessages` with a hash of faulty attributes mapped to their error messages

### PR DESCRIPTION
**Pull request by ceslami**
@jmileham @samandmoore @reustmd 

Decided to just do it as a separate PR.

### CODE REVIEW

**Comment by samandmoore** [comment]
Why change this? And why camelcase?

**Comment by ceslami** [comment]
Well, we have to process it in camelcase because thats how our trading API returns it!

**Comment by jmileham** [comment]
Our trading API should have no bearing on the design or behavior of Her, right?  We are only making changes to her that we believe to be better, globally.

**Comment by samandmoore** [comment]
This seems like we're coupling our version of her to how _one_ of our
internal APIs works. Shouldn't the trading API mixin use a middleware that
converts to the way her expect things to work?

--
Sam

**Comment by ceslami** [comment]
@samandmoore @jmileham that sounds fine.

**Comment by ceslami** [comment]
Carded: https://trello.com/c/HMqRfUnx/171-write-some-code-to-make-sure-that-errormessages-key-returned-from-the-trading-api-is-turned-into-errors-and-gets-its-messages-fl

**Pull request closed without merging**
