### PR TITLE
Include error code in Error message when there is a RecordInvalid exception

### PR DESCRIPTION
**Pull request by ceslami**
@reustmd @LucasSantoro @samandmoore @jmileham

### CODE REVIEW

**Comment by samandmoore** [comment]
What's the reasoning for this? Seems like this surfacing a thing that should just always be true

**Comment by ceslami** [comment]
We standardized around including status codes in the Error message but I did not do so for this one.

**Comment by ceslami** [comment]
I truly don't need it for my feature to work so if its an issue I can happily close it. Just thought I'd take the opportunity to introduce some consistency.

**Comment by reustmd** [comment]
seems fine. lgtm.

**Pull request merged**
