### PR TITLE
created ErrorCollection, constructing it when response comes back with errors

### PR DESCRIPTION
**Pull request by adamlangsner**
/platform @jmileham @samandmoore 
/domain @ceslami 
/cc @abenke @alederman

### CODE REVIEW

**Comment by ceslami** [comment]
Can you expound upon the problem a bit more, preferably with a concrete use-case?

**Comment by ceslami** [comment]
<< domain

**Comment by adamlangsner** [comment]
@ceslami i dont hace a use case. this is just how @jmileham wants it done so that it acts more like hot ActiveRecord would in an analogous case

**Comment by jmileham** [comment]
For a little background, I asked @adamlangsner to do this because it seems to be one of the last vestiges of default-her behavior that completely gloss over some classes of server error.  The default behavior used to be "I tried to fetch this collection, got an error back, but it presents as an empty collection to my app".  This could have such terrible repercussions as us deleting the entire set of YodleeSites if their API goes down or does something weird, crippling our yodlee integration.  So I'd argue you do have a use case, @adamlangsner, but whatevsies. :)

**Comment by ceslami** [comment]
Thanks @jmileham, makes sense. 

@adamlangsner I like that you have a unit test of the ErrorCollection's behavior in isolation, but I would like to see a webmock-driven unit test as well. It may be best off living in `orm_spec.rb`.

**Comment by ceslami** [comment]
TAFN

**Comment by samandmoore** [comment]
@jmileham @adamlangsner does the work that @ceslami did for non-200 http responses not translate into the collection http operations?

**Comment by jmileham** [comment]
it appears not because I saw a test in @adamlangsner's code that was exercising the error case.

**Comment by ceslami** [comment]
The 500-space exception should be fine for collections, but the 400-space exceptions are specific to models.

**Comment by adamlangsner** [comment]
bump. added test to `orm_spec.rb`

**Comment by jmileham** [comment]
<< platform

**Comment by jmileham** [comment]
platformlgtm!

**Comment by ceslami** [comment]
@jmileham given that the error message does not contain the class name containing the ErrorCollection, is the message a little bit too broad to provide useful Errbit bucketing? I would assume that we want each class to get its own bucket when it encounters a collection error.

**Comment by jmileham** [comment]
You'll get a bucket per distinct stack trace regardless, so it should be pretty diagnosable.  The biggest thing to be careful of is not breaking the bucketing.

**Comment by ceslami** [comment]
@jmileham awesome, thanks.

DomainLGTM

**Pull request merged**
